CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE AIINDEXJOB (
  indexJobId SERIAL PRIMARY KEY,
  jobAppId INT NOT NULL,              
  stat VARCHAR(50) NOT NULL,
  retryCount INT NOT NULL DEFAULT 0,
  errorMsg TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  startedAt TIMESTAMP,
  finishedAt TIMESTAMP,
  FOREIGN KEY (jobAppId) REFERENCES JOBAPPLICATION(jobAppId)
);
 
CREATE TABLE CVPARSED (
  cvParsedId SERIAL PRIMARY KEY,
  jobAppId INT NOT NULL UNIQUE,
  rawText TEXT NOT NULL,
  parsedJson JSONB,
  parserVer VARCHAR(50) NOT NULL,
  parseAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobAppId) REFERENCES JOBAPPLICATION(jobAppId)
);
 
CREATE TABLE AIDOCUMENTCHUNK (
  chunkId SERIAL PRIMARY KEY,
  jobAppId INT NOT NULL,
  sourceType VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  chunkIndex INT NOT NULL,
  tokenCount INT NOT NULL,
  metadata JSONB,
  embedding halfvec(1536),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobAppId) REFERENCES JOBAPPLICATION(jobAppId)
);
 
CREATE TABLE AIQUERYLOG (
  queryId SERIAL PRIMARY KEY,
  jobAppId INT NOT NULL,
  hrId INT NOT NULL,
  prompt TEXT NOT NULL,
  response TEXT NOT NULL,
  topK INT NOT NULL,
  latencyMs INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobAppId) REFERENCES JOBAPPLICATION(jobAppId),
  FOREIGN KEY (hrId) REFERENCES HR(userId)
);
